//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiShopTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsView
    {
        public string name { get; set; }
        public int id { get; set; }
        public int amountMAX { get; set; }
        public int amountCurrent { get; set; }
        public int amountMin { get; set; }
        public int idUsers { get; set; }
    }
}
